apiVersion: v1
kind: Pod
metadata:
  name: node1
  labels:
    app: node1
spec:
  containers:
    - name: node1
      image: ansible-node-img
      imagePullPolicy: Never
      ports:
        - containerPort: 22
      securityContext:
        privileged: true

