apiVersion: v1
kind: Pod
metadata:
  name: node2
  labels:
    app: node2
spec:
  containers:
    - name: node2
      image: ansible-node-img
      imagePullPolicy: Never
      ports:
        - containerPort: 22
      securityContext:
        privileged: true

